name: CI Pipeline

on:
  push:
    branches:
      - dev
      - feature/*  # This matches any feature branch
  pull_request:
    branches:
      - dev
      - feature/*  # This ensures that PRs to dev and feature branches are checked

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run Maven Tests
        run: mvn test --no-transfer-progress

#  lint:
#    name: Check Code Format
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Run Checkstyle
#        run: mvn checkstyle:check --no-transfer-progress

  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean install --no-transfer-progress
